# Generated by Django 2.0 on 2017-12-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='eturismo/static/img/barra-do-cunhau.jpg', null=True, upload_to='static/img', verbose_name='Imagem'),
        ),
    ]
