# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='imagem',
        ),
        migrations.AddField(
            model_name='promocao',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='imagens/perfil/noperfil.png', null=True, upload_to='imagens/perfil', verbose_name='Imagem'),
        ),
    ]
