# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passeios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=250, verbose_name='Localização')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
                ('Municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio')),
                ('Tipo_Passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_Passeio')),
            ],
        ),
    ]
