# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171206_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=2, verbose_name='Nota')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
            ],
        ),
    ]
