# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passeios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passeios',
            new_name='Passeio',
        ),
    ]
