# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171218_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='/core/static/img/barra-do-cunhau.jpg', null=True, upload_to='static/img', verbose_name='Imagem'),
        ),
    ]
