# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171219_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='Distrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Distrito'),
        ),
    ]
